import Link from "next/link";
import { signOut } from "@/app/auth/actions";
import type { CustomerAccount, MembershipDeliveryEntitlement } from "@/lib/db/schema";
import type { CustomerOrder, MembershipRequest } from "@/lib/db/schema";
import type { MembershipPurchaseSnapshot } from "@/lib/membership-request";

const money = (value: number) => `฿${value.toLocaleString("en-US")}`;
const date = (value: Date | string | null | undefined) => value ? new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value)) : "Not set";
const statusLabel = (status: string) => status === "payment_received" ? "PENDING REVIEW" : status.replaceAll("_", " ").toUpperCase();

function Meter({ value, max, label }: { value: number; max: number; label: string }) {
  const percentage = max > 0 ? Math.min(100, Math.max(0, Math.round((value / max) * 100))) : 0;
  return <div><div className="flex justify-between gap-4 text-sm"><span>{label}</span><span className="text-gold">{percentage}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-foreground/10"><div className="h-full rounded-full bg-gold transition-[width]" style={{ width: `${percentage}%` }} /></div></div>;
}

function Empty({ children }: { children: React.ReactNode }) {
  return <p className="border-t border-border/50 pt-5 text-sm text-muted-foreground">{children}</p>;
}

export function CustomerDashboard({ account, membership, orders, deliveryEntitlements }: { account: CustomerAccount; membership: MembershipRequest | null; orders: CustomerOrder[]; deliveryEntitlements: MembershipDeliveryEntitlement[] }) {
  const firstName = account.fullName?.trim().split(/\s+/)[0] || "there";
  const active = membership?.status === "active";
  const start = membership?.membershipStartDate;
  const expiry = membership?.membershipExpiryDate;
  const invoiceStatus = membership?.invoiceStatus === "paid" ? "PAID" : membership?.invoiceStatus ? statusLabel(membership.invoiceStatus) : "NOT ISSUED";
  const planSnapshot = membership?.finalMembershipSnapshot && typeof membership.finalMembershipSnapshot === "object" ? membership.finalMembershipSnapshot as Record<string, unknown> : null;
  const packageConfig = membership?.configuration && typeof membership.configuration === "object" ? membership.configuration as Record<string, unknown> : null;
  const finalSnapshot = membership?.finalMembershipSnapshot && typeof membership.finalMembershipSnapshot === "object" ? membership.finalMembershipSnapshot as { purchase?: MembershipPurchaseSnapshot } : null;
  const purchaseSnapshot = active && finalSnapshot?.purchase
    ? finalSnapshot.purchase
    : membership?.purchaseSnapshot && typeof membership.purchaseSnapshot === "object" ? membership.purchaseSnapshot as MembershipPurchaseSnapshot : null;
  const fulfilledDeliveries = deliveryEntitlements.filter((delivery) => delivery.status === "fulfilled").length;
  const remainingDeliveries = deliveryEntitlements.length - fulfilledDeliveries;
  const nextScheduledDelivery = deliveryEntitlements.find((delivery) => delivery.status === "scheduled" && delivery.scheduledDate);

  return <div className="mx-auto max-w-7xl px-5 pb-28 pt-28 sm:px-8 sm:pt-36"><div className="flex flex-wrap items-end justify-between gap-6 border-b border-border/60 pb-10"><div><p className="text-eyebrow text-gold">Customer portal</p><h1 className="mt-4 font-display text-5xl font-light italic sm:text-7xl">Welcome, {firstName}</h1><p className="mt-4 max-w-xl text-base text-muted-foreground">Here is your Sanbay Fusion membership overview.</p></div><form action={signOut}><button className="rounded-full border border-foreground/30 px-5 py-3 text-eyebrow transition-colors hover:border-gold hover:text-gold">SIGN OUT</button></form></div>
    {!membership && <section className="mt-10 rounded-sm border border-gold/50 bg-gold/5 p-7 sm:p-10"><p className="text-eyebrow text-gold">Membership</p><h2 className="mt-4 font-display text-3xl font-light italic">No Active Membership</h2><p className="mt-3 max-w-xl text-sm text-foreground/75">You do not currently have an active Sanbay Fusion membership.</p><Link href="/plans" className="mt-7 inline-flex rounded-full bg-gold px-6 py-3 text-eyebrow text-gold-foreground">VIEW MEMBERSHIP PLANS</Link></section>}
    {membership && <><section className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="rounded-sm border border-gold/50 bg-gold/5 p-6"><p className="text-eyebrow text-gold">Membership</p><h2 className="mt-5 font-display text-2xl font-light italic">{membership.planName}</h2><p className="mt-3 text-sm text-gold">{statusLabel(membership.status)}</p><p className="mt-5 text-xs text-muted-foreground">Valid until</p><p className="mt-1 text-sm">{date(expiry)}</p></article><article className="rounded-sm border border-border/60 bg-card/30 p-6"><p className="text-eyebrow text-gold">Delivery allowance</p><p className="mt-5 font-display text-3xl font-light">{membership.deliveryDays} <span className="text-base text-muted-foreground">/ month</span></p><p className="mt-3 text-sm text-muted-foreground">{deliveryEntitlements.length ? `${remainingDeliveries} remaining · ${fulfilledDeliveries} fulfilled this membership month.` : active ? "This membership predates delivery tracking; contact the team to reconcile its current allowance." : "Delivery scheduling becomes available after activation."}</p></article><article className="rounded-sm border border-border/60 bg-card/30 p-6"><p className="text-eyebrow text-gold">Total paid</p><p className="mt-5 font-display text-3xl font-light">{money(membership.estimatedTotal)}</p><p className="mt-3 text-sm text-gold">{invoiceStatus}</p><p className="mt-1 text-xs text-muted-foreground">{purchaseSnapshot?.purchaseMode === "membership_with_package" ? "Membership + prepaid annual package" : "Membership fee only"}</p></article><article className="rounded-sm border border-border/60 bg-card/30 p-6"><p className="text-eyebrow text-gold">Next delivery</p><p className="mt-5 font-display text-2xl font-light italic">{nextScheduledDelivery?.scheduledDate ? date(nextScheduledDelivery.scheduledDate) : deliveryEntitlements.length ? "Schedule pending" : "Not scheduled"}</p><p className="mt-3 text-sm text-muted-foreground">{nextScheduledDelivery ? "Included under your membership delivery entitlement." : "Your team will confirm delivery dates against the plan schedule."}</p></article></section>
      {membership.status === "payment_received" && <section className="mt-8 rounded-sm border border-gold/50 bg-gold/5 p-6 sm:p-8"><p className="text-eyebrow text-gold">Paid · pending review</p><h2 className="mt-3 font-display text-2xl font-light italic">Your membership is under final review</h2><p className="mt-3 text-sm leading-relaxed">Your payment has been received. Our team will review your membership and contact you within up to 3 days. Your Member ID and ordering access will become available after approval.</p></section>}
      {(membership.status === "awaiting_payment" || membership.status === "invoice_issued") && <section className="mt-8 rounded-sm border border-gold/50 bg-gold/5 p-6 sm:p-8"><p className="text-eyebrow text-gold">Payment required</p><h2 className="mt-4 font-display text-3xl font-light italic">Membership Payment Required</h2><p className="mt-3 text-sm">Your membership invoice is due by {date(membership.paymentDueAt)}.</p>{membership.invoiceNumber && <p className="mt-2 text-sm text-muted-foreground">Invoice {membership.invoiceNumber}</p>}</section>}
      {membership.status === "membership_setup" && <section className="mt-8 rounded-sm border border-gold/50 bg-gold/5 p-6 sm:p-8"><p className="text-eyebrow text-gold">Setup in progress</p><h2 className="mt-4 font-display text-3xl font-light italic">Membership Setup In Progress</h2><p className="mt-3 text-sm">Payment received. Our team is preparing your membership details.</p></section>}
      {active && <section className="mt-8 grid gap-8 border-y border-border/60 py-8 lg:grid-cols-2"><div><p className="text-eyebrow text-gold">Membership period</p><div className="mt-5 flex justify-between gap-4 text-sm text-muted-foreground"><span>{date(start)}</span><span>{date(expiry)}</span></div></div><div><p className="text-eyebrow text-gold">Delivery usage this membership month</p>{deliveryEntitlements.length ? <><div className="mt-5"><Meter value={fulfilledDeliveries} max={deliveryEntitlements.length} label={`${fulfilledDeliveries} / ${deliveryEntitlements.length} fulfilled`} /></div><p className="mt-5 text-sm text-muted-foreground">Remaining: {remainingDeliveries} delivery {remainingDeliveries === 1 ? "day" : "days"}.</p></> : <p className="mt-5 text-sm text-muted-foreground">No delivery ledger is available for this membership month.</p>}</div></section>}
      {active && purchaseSnapshot?.purchaseMode === "membership_with_package" && <section className="mt-8 rounded-sm border border-border/60 bg-card/30 p-6 sm:p-8"><p className="text-eyebrow text-gold">Prepaid annual package</p><p className="mt-2 text-sm text-muted-foreground">Included for {purchaseSnapshot.delivery.deliveriesPerYear} scheduled deliveries. These items are not charged again when fulfilled under this agreement.</p><div className="mt-5 divide-y divide-border/50">{purchaseSnapshot.products.map((product) => <div key={`${product.category}:${product.name}`} className="flex flex-wrap justify-between gap-3 py-3 text-sm"><span>{product.name}<span className="ml-2 text-xs text-muted-foreground">{product.category} · {product.quantityPerDelivery} per delivery · {product.annualQuantity} annually</span></span><span>{money(product.lineTotal)} prepaid</span></div>)}{purchaseSnapshot.addOns.map((addon) => <div key={`${addon.category}:${addon.name}`} className="flex justify-between gap-3 py-3 text-sm"><span>{addon.name} · add-on</span><span>{money(addon.lineTotal)} prepaid</span></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Extra orders outside this package are charged separately through Place Order.</p></section>}
      <div className="mt-10 grid gap-10 lg:grid-cols-[1.15fr_0.85fr]"><section><p className="text-eyebrow text-gold">My membership</p><div className="mt-5 grid gap-x-8 gap-y-5 border-y border-border/60 py-6 text-sm sm:grid-cols-2"><div><p className="text-muted-foreground">Membership plan</p><p className="mt-1">{membership.planName}</p></div><div><p className="text-muted-foreground">Member ID</p><p className="mt-1">{membership.membershipNumber ?? "Pending issuance"}</p></div><div><p className="text-muted-foreground">Status</p><p className="mt-1">{statusLabel(membership.status)}</p></div><div><p className="text-muted-foreground">Membership term</p><p className="mt-1">{membership.validityMonths} months</p></div><div><p className="text-muted-foreground">Start date</p><p className="mt-1">{date(start)}</p></div><div><p className="text-muted-foreground">Expiry date</p><p className="mt-1">{date(expiry)}</p></div><div><p className="text-muted-foreground">Monthly entitlement</p><p className="mt-1">{membership.deliveryDays} days</p></div><div><p className="text-muted-foreground">Annual entitlement</p><p className="mt-1">{membership.annualDeliveryDays} days</p></div></div></section><section><p className="text-eyebrow text-gold">My finalized package</p><div className="mt-5 border-y border-border/60 py-6 text-sm"><p className="text-muted-foreground">Snapshot status</p><p className="mt-1">{purchaseSnapshot?.purchaseMode === "membership_with_package" ? (active ? "Prepaid package active" : "Prepaid package pending approval") : "No prepaid annual package"}</p>{packageConfig && <p className="mt-5 text-muted-foreground">Selected preferences: <span className="text-foreground">{Array.isArray(packageConfig.foodPreferences) ? packageConfig.foodPreferences.join(", ") || "None" : "Recorded"}</span></p>}<Link href="/membership" className="mt-6 inline-flex text-eyebrow text-gold underline">VIEW FULL MEMBERSHIP</Link></div></section></div>
      <div className="mt-12 grid gap-10 lg:grid-cols-2"><section id="invoices"><p className="text-eyebrow text-gold">Invoices & payments</p>{membership.invoiceNumber ? <div className="mt-5 rounded-sm border border-border/60 bg-card/30 p-6 text-sm"><div className="flex justify-between gap-4"><span>{membership.invoiceNumber}</span><span className="text-gold">{invoiceStatus}</span></div><p className="mt-5 text-muted-foreground">Membership Fee</p><p className="mt-1 text-2xl">{money(membership.estimatedTotal)}</p><p className="mt-5 text-muted-foreground">Issued {date(membership.invoiceIssuedAt)}</p></div> : <div className="mt-5"><Empty>No invoices yet.</Empty></div>}</section><section><p className="text-eyebrow text-gold">Recent orders</p>{orders.length === 0 ? <div className="mt-5"><Empty>You have not placed any orders yet.</Empty></div> : <div className="mt-5 space-y-4">{orders.map((order) => <div key={order.id} className="rounded-sm border border-border/60 bg-card/30 p-4 text-sm"><div className="flex items-center justify-between gap-3"><span className="font-medium">{order.orderNumber}</span><span className="text-gold">{order.paymentStatus.toUpperCase()}</span></div><div className="mt-3 flex items-center justify-between gap-3 text-muted-foreground"><span>{date(order.createdAt)}</span><span>{money(order.total)}</span></div><div className="mt-2 text-xs uppercase tracking-[0.12em] text-gold">{order.status}</div></div>)}</div>}<p className="mt-10 text-eyebrow text-gold">Delivery overview</p><div className="mt-5">{deliveryEntitlements.filter((delivery) => delivery.status === "scheduled").map((delivery) => <p key={delivery.id} className="border-t border-border/50 py-3 text-sm">{delivery.scheduledDate ? date(delivery.scheduledDate) : "Scheduled delivery"} · Included membership delivery</p>)}{!deliveryEntitlements.some((delivery) => delivery.status === "scheduled") && <Empty>No delivery currently scheduled.</Empty>}</div></section></div>
      <section className="mt-12 border-t border-border/60 pt-8"><p className="text-eyebrow text-gold">Quick actions</p><div className="mt-5 flex flex-wrap gap-3"><Link href="/dashboard/order" aria-disabled={!active} className={active ? "rounded-full bg-gold px-5 py-3 text-eyebrow text-gold-foreground hover:bg-gold/85" : "pointer-events-none rounded-full border border-foreground/20 bg-foreground/5 px-5 py-3 text-eyebrow text-muted-foreground opacity-60"}>PLACE ORDER</Link><Link href="/membership" className="rounded-full border border-foreground/30 px-5 py-3 text-eyebrow hover:border-gold hover:text-gold">VIEW MEMBERSHIP</Link><Link href="#invoices" className="rounded-full border border-foreground/30 px-5 py-3 text-eyebrow hover:border-gold hover:text-gold">VIEW INVOICES</Link></div></section></>}
  </div>;
}