import Link from "next/link";
import type { PaymentMethodSummary } from "@/lib/membership-application-types";
import { signOut } from "@/app/auth/actions";
import type { CustomerAccount, CustomerOrder, MembershipRequest, MembershipDeliveryEntitlement } from "@/lib/db/schema";
import type { MembershipPurchaseSnapshot } from "@/lib/membership-request";
import { hasActiveMembership, membershipDaysRemaining } from "@/lib/membership-term";
import { PackageSummary } from "@/components/membership/package-summary";

const money = (value: number) => `฿${value.toLocaleString("en-US")}`;
const date = (value: Date | string | null | undefined) => value ? new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Bangkok", day: "numeric", month: "long", year: "numeric" }).format(new Date(value)) : "Pending activation";
const statusLabel = (value: string) => value === "payment_received" ? "PENDING REVIEW" : value.replaceAll("_", " ").toUpperCase();

export function CustomerDashboard({ account, membership, orders, deliveryEntitlements }: { account: CustomerAccount; membership: MembershipRequest | null; orders: CustomerOrder[]; deliveryEntitlements: MembershipDeliveryEntitlement[] }) {
  const active = hasActiveMembership(membership);
  const final = membership?.finalMembershipSnapshot as { purchase?: MembershipPurchaseSnapshot } | null;
  const snapshot = final?.purchase ?? membership?.purchaseSnapshot as MembershipPurchaseSnapshot | null;
  const method = membership?.paymentMethodSummary as PaymentMethodSummary | null;
  const remaining = membershipDaysRemaining(membership?.membershipExpiryDate ?? null);
  return <div className="mx-auto max-w-7xl px-5 pb-28 pt-28 sm:px-8 sm:pt-36">
    <div className="flex flex-wrap justify-between gap-6 border-b border-border/60 pb-10"><div><p className="text-eyebrow text-gold">Customer portal</p><h1 className="mt-4 font-display text-5xl font-light italic">Welcome, {account.fullName?.split(/\s+/)[0] || "there"}</h1></div><form action={signOut}><button className="rounded-full border border-foreground/30 px-5 py-3 text-eyebrow">SIGN OUT</button></form></div>
    {!membership ? <section className="mt-10 space-y-5"><h2 className="font-display text-3xl">No Active Membership</h2><Link href="/plans" className="text-gold underline">VIEW MEMBERSHIP PLANS</Link></section> : <>
      <section className="mt-10 rounded-sm border border-gold/50 bg-gold/5 p-7"><p className="text-eyebrow text-gold">Membership status</p><p className="mt-3 text-xl">{statusLabel(membership.status)}</p><dl className="mt-6 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {[["Plan", membership.planName], ["Membership Duration", `${membership.durationMonths} ${membership.durationMonths === 1 ? "Month" : "Months"}`], ["Member ID", membership.membershipNumber ?? "Not issued"], ["Start Date", date(membership.membershipStartDate)], ["Expiry Date", date(membership.membershipExpiryDate)], ["Time Remaining", active ? `${remaining} ${remaining === 1 ? "day" : "days"}` : membership.status === "expired" ? "Expired" : "Not active"]].map(([label, value]) => <div key={label}><dt className="text-sm text-muted-foreground">{label}</dt><dd className="mt-2">{value}</dd></div>)}
      </dl></section>
      {membership.applicationSnapshot != null && <section className="mt-8 space-y-4 border border-gold/40 p-6"><h2 className="text-eyebrow text-gold">MEMBERSHIP APPLICATION</h2><p>{membership.invoiceStatus === "paid" ? "PAID" : "NOT YET CHARGED"}</p>{method && <p className="capitalize">{method.brand} **** {method.last4} / Expires {method.expMonth}/{method.expYear}</p>}{membership.status === "pending_review" && <p>Your application is awaiting review. The displayed amount will be charged only if approved.</p>}{membership.status === "declined" && <p>Your application was declined. No membership charge was made.</p>}{membership.status === "application_draft" && <Link href={`/membership/checkout?application=${membership.id}`} className="text-gold underline">Continue application</Link>}{membership.status.startsWith("approved_payment_") && <><p>{membership.paymentFailure ?? "Your authorized payment is being processed."}</p><Link href={`/membership/payment?id=${membership.id}`} className="text-gold underline">Confirm or update payment</Link></>}</section>}
      {!membership.applicationSnapshot && membership.status === "payment_received" && <section className="mt-8 border border-gold/40 p-6"><h2 className="text-eyebrow text-gold">PAID · PENDING REVIEW</h2><p className="mt-4 text-sm">Our team will review your details and contact you within up to 3 days. Your Member ID is issued and your selected term begins only after final approval.</p></section>}
      {membership.status === "expired" && <section className="mt-8 border border-border/60 p-6"><h2 className="font-display text-2xl">Your membership has expired</h2><p className="mt-3 text-sm">Ordering access has ended. Choose any 1 to 12 month plan to purchase a new term.</p><Link href="/plans" className="mt-5 inline-flex rounded-full bg-gold px-6 py-3 text-eyebrow text-gold-foreground">RENEW MEMBERSHIP</Link></section>}
      {snapshot && <div className="mt-8 rounded-sm border border-border/60 p-6 sm:p-8"><PackageSummary snapshot={snapshot} /></div>}
      <section id="invoices" className="mt-8 grid gap-6 border-y border-border/60 py-7 sm:grid-cols-3"><div><p className="text-sm text-muted-foreground">Payment Status</p><p className="mt-2 text-gold">{membership.invoiceStatus === "paid" ? "PAID" : membership.applicationSnapshot ? "NOT YET CHARGED" : statusLabel(membership.invoiceStatus ?? "awaiting_payment")}</p></div><div><p className="text-sm text-muted-foreground">Membership Fee</p><p className="mt-2">{money(snapshot?.membershipFee ?? membership.annualFee)}</p></div><div><p className="text-sm text-muted-foreground">{membership.invoiceStatus === "paid" ? "Total Paid" : "Expected Amount"}</p><p className="mt-2">{money(membership.estimatedTotal)}</p></div></section>
      {deliveryEntitlements.length > 0 && <section className="mt-8"><h2 className="text-eyebrow text-gold">Historical delivery schedule</h2><div className="mt-4 space-y-3">{deliveryEntitlements.map(item => <p key={item.id} className="text-sm">{item.scheduledDate ? date(item.scheduledDate) : "Date to be arranged"} · {statusLabel(item.status)}</p>)}</div></section>}
      <section className="mt-8"><h2 className="text-eyebrow text-gold">Quick actions</h2><div className="mt-5 flex flex-wrap gap-4">{!active && <button disabled className="rounded-full border border-foreground/20 px-6 py-3 text-eyebrow opacity-40">PLACE ORDER</button>}{active && <Link href="/dashboard/order" className="rounded-full bg-gold px-6 py-3 text-eyebrow text-gold-foreground">PLACE ORDER</Link>}<Link href="/plans" className="rounded-full border border-foreground/30 px-6 py-3 text-eyebrow">VIEW PLANS</Link></div></section>
    </>}
    <section className="mt-12"><h2 className="text-eyebrow text-gold">Recent orders</h2><div className="mt-5 space-y-4">{orders.length === 0 ? <p className="text-sm text-muted-foreground">No orders yet.</p> : orders.map(order => <article key={order.id} className="flex flex-wrap justify-between gap-4 border border-border/60 p-5 text-sm"><span>{order.orderNumber} · {date(order.createdAt)}</span><span>{money(order.total)} · {statusLabel(order.paymentStatus)}</span></article>)}</div></section>
  </div>;
}
