import type { Metadata } from "next";
import Link from "next/link";
import { PageHeader } from "@/components/site/page-header";
import { membershipPlans } from "@/lib/membership-plans";
import { membershipEligibilityNotice } from "@/lib/membership-eligibility";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "FAQ", description: "Eligibility for foreign visitors to Thailand, travel service months, Standard Meals, application review, payments and support.", alternates: { canonical: "/faq" } };
const baht = (value: number) => "฿" + value.toLocaleString("en-US");
const sections = [
  { title: "International-visitor eligibility", questions: [
    ["Who can apply for Sanbay Fusion Membership?", membershipEligibilityNotice + " Eligible customers include tourists, holidaymakers, business travellers, returning international visitors and foreign customers planning an extended temporary visit. Complete Account Center, confirm eligibility and submit your application for review."],
    ["Is membership available to Thai domestic customers?", "No. This particular website membership program is not offered to domestic Thai customers. A Thailand delivery address does not establish visitor eligibility. The restriction applies to this membership program; separate meeting, event and support enquiries retain their own arrangements."],
    ["Can I arrange membership before travelling to Thailand?", "Yes. Eligible foreign visitors may plan before travelling or while temporarily in Thailand. Just as you arrange accommodation and transport, you can select service months, configure eligible meals and services, and schedule Standard Meals now or later. Approval, payment and availability requirements still apply."],
    ["Can I select different months based on my travel schedule?", "Yes. Select the number of eligible service months in your plan within one calendar year; they may be non-consecutive. This can support separate visits. Choose eligible months in the current or next year and review the dates carefully before final submission."],
    ["Does submitting an application guarantee approval?", "No. Account creation and application submission do not create an active membership. The team reviews visitor eligibility, account details, delivery information and selections and may contact you for clarification. Only an approved application proceeds to collection of the authorized amount; activation requires verified successful payment."],
  ] },
  { title: "Getting started", questions: [
    ["What is Sanbay Fusion?", site.legalName + " created this membership service specifically for foreign visitors who normally live outside Thailand and visit temporarily. Meeting and private-event enquiries are handled separately by the team. Current delivery coverage is Bangkok, subject to address validation."],
    ["How do I create an account?", "Use Sign Up to enter your details, choose and confirm a password that meets the displayed requirements, and accept the required terms. If you already have an account, sign in. Continue in Account Center to complete the required personal, billing, delivery and payment information."],
    ["How do the 1–12 month plans work?", "Choose a plan for 1 to 12 selected service months. The one-time membership fee ranges from " + baht(membershipPlans[0].price) + " for one month to " + baht(membershipPlans[11].price) + " for twelve months. Longer plans have higher total fees and lower effective monthly fees. Plan pages show the current fee and included Standard Meal allowance."],
    ["Can my service months be different months?", "Yes. Choose exactly the number of months in your plan, within one calendar year. You can choose eligible months in the current or next year; they need not be consecutive. Past months and dates that cannot meet the scheduling notice are unavailable. Your selected months are fixed when you submit the final application."],
    ["What is included with membership?", "Each selected service month includes one Standard Meal allowance at the value displayed for your plan. Membership also enables eligible member ordering during selected months after activation. Optional prepaid packages and additional orders are separate from that allowance."],
  ] },
  { title: "Standard Meals and additional orders", questions: [
    ["How does the included Standard Meal work?", "Schedule a date and time for the selected month, then start that month's Standard Meal order from your dashboard during that service month. Choose eligible food. Your saved plan allowance is applied to one meal order, up to its food total. Scheduling alone does not place or redeem the order."],
    ["What if my meal exceeds the included allowance?", "Checkout shows the allowance applied and the excess you must pay. If eligible food costs less than the allowance, there is no food charge for that order, but the unused balance is not cash or credit and cannot be carried into another order. Drinks and other non-food items must be ordered separately."],
    ["Can I schedule my meal later?", "Yes. Select Schedule later during configuration, then use Account Center to choose a slot. Future selected months can be scheduled in advance. Meal orders themselves must be placed in the corresponding selected month."],
    ["What delivery notice and times apply?", "Standard Meal dates require at least three calendar days' notice and must fall within the selected month. Available time choices run from 11:00 AM to midnight in 30-minute steps, using Bangkok time. Midnight closes the selected delivery day. Requests remain subject to team confirmation and availability."],
    ["How do additional orders work?", "During an active selected service month, open member ordering in your dashboard, choose eligible products and review the checkout total. Additional orders are paid separately. Ordering is unavailable in unselected months or after expiry; the server validates your membership and prices."],
    ["How are prepaid package quantities calculated?", "Monthly product cost is unit price × monthly quantity × selected service months. Monthly add-ons follow the same rule; one-time add-ons are charged once. Four units per month means four products, not four delivery visits. Paid package quantities are separate from the included Standard Meal."],
    ["Can I change a package or carry unused benefits forward?", "Review your selections carefully before submission. Finalized packages are ordinarily locked after activation; contact the team about exceptions or unavailable items. Standard Meal benefits do not accumulate or roll over. Any arrangements for unused prepaid quantities must follow your agreed terms."],
    ["What about allergies, unavailable products or a problem with delivery?", "Share allergies and dietary requirements before ordering and obtain confirmation from the team. Availability and substitutions may need discussion. Contact us promptly about incorrect, damaged or unsafe food so the team can review the appropriate remedy."],
    ["Can I add alcohol to a membership?", "Alcohol is excluded from the current membership application and prepaid package flow. A catalogue listing does not establish eligibility to purchase or deliver a regulated product. Contact the team about any separate event requirements."],
  ] },
  { title: "Review, payment and Account Center", questions: [
    ["How is my application reviewed?", "Submission records your selected months, configuration, addresses, agreed amount and payment authorization and creates a draft invoice. The team reviews your application and may contact you to verify details. Track its status in Account Center; approval and payment are separate steps."],
    ["When am I charged?", "Application submission does not collect the membership fee. After approval, staff can collect the exact authorized invoice amount. Approval alone does not charge or activate membership. Card verification is a separate USD $2 payment, refunded after successful verification. Online payments currently operate in test mode; live card payments are not available."],
    ["When does membership become active?", "After the application is approved and successful payment is verified, membership activates and your Member ID is issued. Benefits and ordering still apply only during selected service months. An approved but unpaid application is not an active membership."],
    ["Where can I see my membership and order status?", "Sign in and open Account Center. Your dashboard shows applications, membership details and Member ID, selected months, Standard Meal status, orders and payment records."],
    ["How do saved payment methods work?", "Cards are entered through Stripe. Account Center uses a USD $2 verification payment and initiates a refund after successful verification; bank display times vary. Choose a verified card as your default before applying. Sanbay Fusion stores safe references such as card brand, last four digits and expiry, not complete card numbers or CVC."],
    ["How do I update billing and delivery information?", "Use the billing and delivery address sections in Account Center. Your final application keeps the addresses you accepted when submitting. Changing your saved address does not rewrite an existing agreement or order; contact the team about changes to those arrangements."],
    ["What if my payment needs additional authentication?", "Follow the payment action shown in Account Center to complete your bank's authentication. If no action is available or you cannot complete it, contact the team with your application reference. Membership remains inactive until payment is verified."],
    ["What happens if payment fails?", "Check the status in Account Center and contact the team about retrying the approved invoice or reviewing the payment method. Updating your default card does not silently change an already submitted payment agreement. Do not submit duplicate applications to resolve a payment problem."],
  ] },
  { title: "Cancellation, expiry and help", questions: [
    ["How do cancellations work?", "Contact the team with your application or Member ID to request cancellation. The team must review the request and confirm its effect on service and outstanding orders. Sending a request does not automatically cancel an invoice, end access or issue a refund."],
    ["What is refundable or non-refundable?", "Under the membership terms, the membership fee is non-refundable after payment and activation except where applicable law requires a remedy. Cancellation does not automatically refund unused benefits or prepaid quantities. The separate USD $2 card verification is refunded after successful verification. Contact the team about disputed or incorrect charges and product problems."],
    ["When does membership expire?", "For current plans, the term ends at the start of the day after your last selected calendar month, in Bangkok time. Benefits are available only in selected months. There is no automatic renewal or recurring membership charge. Historical agreements retain their saved terms."],
    ["Can I buy another membership while mine is ongoing?", "You cannot buy another membership while your existing membership is ongoing or has selected service months remaining, including gaps between months. After expiry, review the available plans and submit a new application."],
    ["How do I contact Sanbay Fusion?", "Call " + site.phone + ", email " + site.email + ", or use our Contact page for the official business location and enquiry form. Include your application or order reference when asking about an existing request; never send card details, passwords or security codes."],
    ["How are reservations and private events handled?", "The Reservations page lets you request a meeting. Private Events & Bespoke Hospitality lets you build a brief for dinners, celebrations, villa or residence occasions and business gatherings in Thailand, before or during your visit. Share the occasion, location, dining, beverages, entertainment and contact details; our team reviews availability and logistics before preparing a tailored proposal. Submission does not confirm an event, guarantee availability, create a final quote or charge you. Alcoholic beverage requirements are discussed separately, not purchased through the form."],
  ] },
];

export default function FAQPage() {
  return <div className="pb-28"><PageHeader eyebrow="Questions" title="Know what happens next" lead="Membership for international visitors: check eligibility, plan around your trip and understand review, meals and payment before applying." /><div className="mx-auto max-w-3xl px-5 sm:px-8">
    <nav aria-label="FAQ topics" className="mb-12 flex flex-wrap gap-3">{sections.map((section, index) => <a key={section.title} href={index === 0 ? "#membership-eligibility" : "#faq-" + index} className="rounded-full border border-border/60 px-4 py-2 text-sm hover:border-gold">{section.title}</a>)}</nav>
    {sections.map((section, index) => <section key={section.title} id={index === 0 ? "membership-eligibility" : "faq-" + index} className="mb-16 scroll-mt-28"><h2 className="text-eyebrow text-gold">{section.title}</h2><div className="mt-4 divide-y divide-border/50">{section.questions.map(([question, answer]) => <details key={question} className="group py-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 rounded-sm font-display text-2xl focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-gold"><span>{question}</span><span aria-hidden="true" className="shrink-0 text-gold group-open:rotate-45">+</span></summary><p className="mt-4 text-base leading-7 text-foreground/75">{answer}</p></details>)}</div></section>)}
    <p className="border-t border-border/60 pt-8 text-sm leading-7">Read the <Link href="/terms-and-conditions" className="text-gold underline">membership terms</Link> and <Link href="/privacy-policy" className="text-gold underline">privacy policy</Link>, or <Link href="/contact" className="text-gold underline">contact the team</Link> about your circumstances.</p>
  </div></div>;
}
