export type CatalogueGroup = "food" | "drinks" | "alcohol";

export type CatalogueProduct = {
  name: string;
  price: number;
};

export type CatalogueCategory = {
  name: string;
  group: CatalogueGroup;
  description: string;
  products: CatalogueProduct[];
  indicativeFrom: number;
  vegetarianFriendly?: boolean;
};

const pricedProducts = (names: string[], startingPrice: number): CatalogueProduct[] => names.map((name, index) => ({
  name,
  price: startingPrice + Math.floor(index / 4) * Math.max(20, Math.round(startingPrice * 0.08)),
}));

const thaiStarters = ["Chicken Satay", "Pork Satay", "Shrimp Cakes", "Thai Fish Cakes", "Spring Rolls", "Fried Tofu", "Fried Chicken Wings", "Crispy Shrimp", "Thai Fresh Rolls", "Som Tam", "Larb", "Thai Beef Salad", "Spicy Seafood Salad", "Glass Noodle Salad"];
const thaiSoups = ["Tom Yum Goong", "Tom Yum Chicken", "Tom Yum Seafood", "Tom Kha Gai", "Tom Kha Seafood", "Clear Vegetable Soup", "Clear Pork Soup", "Spicy Beef Soup", "Thai Hot & Sour Soup"];
const thaiCurries = ["Green Curry Chicken", "Green Curry Beef", "Green Curry Pork", "Green Curry Seafood", "Red Curry Chicken", "Red Curry Beef", "Red Curry Pork", "Red Curry Duck", "Massaman Chicken", "Massaman Beef", "Panang Chicken", "Panang Beef", "Yellow Curry Chicken", "Thai Jungle Curry", "Pumpkin Curry"];
const thaiRice = ["Pad Kra Pao Chicken", "Pad Kra Pao Pork", "Pad Kra Pao Beef", "Pad Kra Pao Seafood", "Pad Kra Pao Crispy Pork", "Thai Fried Rice", "Chicken Fried Rice", "Pork Fried Rice", "Beef Fried Rice", "Seafood Fried Rice", "Pineapple Fried Rice", "Crab Fried Rice", "Garlic Rice", "Coconut Rice", "Steamed Jasmine Rice"];
const thaiNoodles = ["Pad Thai Chicken", "Pad Thai Shrimp", "Pad Thai Seafood", "Pad See Ew Chicken", "Pad See Ew Pork", "Pad See Ew Beef", "Pad Kee Mao", "Thai Boat Noodles", "Beef Noodle Soup", "Chicken Noodle Soup", "Drunken Noodles", "Glass Noodles", "Stir-Fried Egg Noodles"];
const thaiSeafood = ["Grilled Prawns", "Garlic Prawns", "Chili Prawns", "Steamed Fish with Lime", "Fried Fish with Chili", "Grilled Sea Bass", "Grilled Squid", "Garlic Squid", "Seafood Hot Pot", "Seafood Platter", "Crab Curry", "Stir-Fried Crab", "Thai Seafood BBQ"];
const thaiMeat = ["Thai BBQ Chicken", "Grilled Pork Neck", "Thai BBQ Pork", "Crispy Pork Belly", "Garlic Pork", "Chili Pork", "Thai Beef BBQ", "Grilled Beef", "Beef Basil", "Beef with Oyster Sauce", "Thai-Style Beef Steak"];
const western = ["Classic Beef Burger", "Double Beef Burger", "Cheese Burger", "BBQ Burger", "Chicken Burger", "Crispy Chicken Burger", "Spicy Chicken Burger", "Premium Beef Burger", "VIP Wagyu Burger", "Margherita Pizza", "Pepperoni Pizza", "Hawaiian Pizza", "Chicken BBQ Pizza", "Seafood Pizza", "Four Cheese Pizza", "Truffle Mushroom Pizza", "Premium Seafood Pizza", "Spaghetti Bolognese", "Carbonara", "Arrabbiata", "Seafood Pasta", "Garlic Prawn Pasta", "Chicken Alfredo", "Beef Pasta", "Pesto Pasta", "Truffle Cream Pasta", "Chicken Steak", "Pork Steak", "Beef Steak", "Sirloin", "Ribeye", "Tenderloin", "T-Bone", "Wagyu Steak", "Eggs & Toast", "Bacon & Eggs", "Sausage & Eggs", "Full Breakfast", "Pancakes", "French Toast", "Omelette", "Breakfast Sandwich"];
const asian = ["Japanese Teriyaki Chicken", "Japanese Beef Teriyaki", "Sushi Selection", "Sashimi Selection", "Ramen", "Udon", "Yakitori", "Korean Fried Chicken", "Korean BBQ", "Bibimbap", "Bulgogi", "Chinese Fried Rice", "Sweet & Sour Chicken", "Kung Pao Chicken", "Dumplings", "Dim Sum", "Vietnamese Pho", "Vietnamese Spring Rolls", "Singapore Noodles", "Malaysian Curry"];
const healthy = ["Vegetable Green Curry", "Vegetable Red Curry", "Tofu Stir Fry", "Vegetable Pad Thai", "Vegetable Fried Rice", "Tofu Basil", "Mixed Vegetable Soup", "Garden Salad", "Caesar Salad", "Greek Salad", "Avocado Salad", "Quinoa Bowl", "Rice & Vegetable Bowl", "Healthy Chicken Bowl", "Healthy Seafood Bowl"];
const snacksDesserts = ["French Fries", "Sweet Potato Fries", "Onion Rings", "Chicken Nuggets", "Chicken Wings", "Garlic Bread", "Cheese Sticks", "Spring Rolls", "Satay", "Edamame", "Nachos", "Mixed Nuts", "Potato Chips", "Thai Snacks", "Mango Sticky Rice", "Coconut Ice Cream", "Thai Tea Ice Cream", "Fried Banana", "Banana Pancake", "Chocolate Cake", "Cheesecake", "Brownie", "Tiramisu", "Fruit Platter", "Mango Dessert", "Coconut Dessert", "Ice Cream Selection"];
const drinks = ["Thai Iced Tea", "Thai Milk Tea", "Thai Iced Coffee", "Lemongrass Drink", "Pandan Drink", "Coconut Water", "Butterfly Pea Drink", "Espresso", "Americano", "Cappuccino", "Latte", "Mocha", "Iced Coffee", "Caramel Latte", "Vanilla Latte", "Green Tea", "Jasmine Tea", "Black Tea", "Earl Grey", "Lemon Tea", "Ginger Tea", "Orange Juice", "Apple Juice", "Pineapple Juice", "Watermelon Juice", "Mango Juice", "Coconut Juice", "Passion Fruit Juice", "Mixed Fruit Juice", "Cola", "Cola Zero", "Lemon-Lime Soda", "Ginger Ale", "Tonic Water", "Soda Water", "Sparkling Water", "Still Water"];

const beers = [
  "Singha Lager - 330 ml", "Singha Reserve Lager - 490 ml", "Chang Classic - 320 ml", "Chang Cold Brew - 490 ml", "Leo Lager - 330 ml", "Leo Reserve - 490 ml", "U Beer - 330 ml", "Heineken Original - 330 ml", "Heineken Silver - 330 ml", "Heineken 0.0 - 330 ml", "Tiger Lager - 330 ml", "Tiger Crystal - 330 ml", "San Miguel Pale Pilsen - 330 ml", "San Miguel Premium All-Malt - 330 ml", "San Miguel Super Dry - 330 ml", "Asahi Super Dry - 330 ml", "Asahi Black - 330 ml", "Sapporo Premium - 330 ml", "Sapporo Black Label - 330 ml", "Kirin Ichiban - 330 ml", "Corona Extra - 330 ml", "Corona Cero - 330 ml", "Peroni Nastro Azzurro - 330 ml", "Budweiser - 330 ml", "Stella Artois - 330 ml", "Carlsberg Danish Pilsner - 330 ml", "Guinness Draught Can - 440 ml", "Guinness Foreign Extra Stout - 330 ml", "Hoegaarden White - 330 ml", "Hoegaarden Rosee - 330 ml", "Erdinger Weissbier - 500 ml", "Paulaner Hefe-Weissbier - 500 ml", "Samuel Adams Boston Lager - 355 ml", "BrewDog Punk IPA - 330 ml", "BrewDog Hazy Jane IPA - 330 ml", "Chimay Blue - 330 ml", "Chimay Grande Reserve - 750 ml", "Duvel Belgian Golden Ale - 330 ml", "Delirium Tremens - 330 ml", "La Chouffe Blonde - 330 ml", "Duvel Tripel Hop - 330 ml", "Hitachino Nest White Ale - 330 ml", "Stone IPA - 355 ml", "Founders All Day IPA - 355 ml", "Thai craft IPA selection - 330 ml", "Thai craft stout selection - 330 ml", "Thai craft sour ale selection - 330 ml", "Imported craft beer mixed case - 6 x 330 ml", "Premium beer gift case - 6 x 330 ml"
];
const wines = [
  "House Cabernet Sauvignon - 750 ml", "Jacob's Creek Reserve Shiraz - 750 ml", "Yellow Tail Reserve Shiraz - 750 ml", "Casillero del Diablo Cabernet Sauvignon - 750 ml", "Concha y Toro Marques de Casa Concha Cabernet Sauvignon - 750 ml", "Penfolds Koonunga Hill Shiraz - 750 ml", "Penfolds Bin 389 Cabernet Shiraz - 750 ml", "Penfolds RWT Bin 798 Shiraz - 750 ml", "Penfolds Grange - 750 ml", "Robert Mondavi Napa Valley Cabernet Sauvignon - 750 ml", "Opus One - 750 ml", "Chateau Lynch-Bages - 750 ml", "Chateau Margaux - 750 ml", "Chateau Mouton Rothschild - 750 ml", "Chateau Haut-Brion - 750 ml", "Antinori Tignanello - 750 ml", "Sassicaia - 750 ml", "Ornellaia - 750 ml", "Gaja Barbaresco - 750 ml", "La Rioja Alta Gran Reserva 904 - 750 ml", "Amarone della Valpolicella - 750 ml", "Cloudy Bay Pinot Noir - 750 ml", "Louis Jadot Bourgogne Pinot Noir - 750 ml", "Domaine de la Romanee-Conti Bourgogne - 750 ml", "House Chardonnay - 750 ml", "Oyster Bay Chardonnay - 750 ml", "Kendall-Jackson Vintner's Reserve Chardonnay - 750 ml", "Cloudy Bay Sauvignon Blanc - 750 ml", "Kim Crawford Sauvignon Blanc - 750 ml", "Villa Maria Private Bin Sauvignon Blanc - 750 ml", "Concha y Toro Marques de Casa Concha Chardonnay - 750 ml", "Gavi di Gavi - 750 ml", "Whispering Angel Rose - 750 ml", "Chateau d'Esclans Rock Angel Rose - 750 ml", "Minuty Prestige Rose - 750 ml", "Miraval Rose - 750 ml", "Mateus Rose - 750 ml", "Moscato d'Asti - 750 ml", "Sauternes dessert wine - 750 ml", "Tokaji Aszu 5 Puttonyos - 500 ml", "Inniskillin Vidal Icewine - 375 ml", "Late harvest Riesling - 750 ml", "Prosecco DOC Brut - 750 ml", "Franciacorta Brut - 750 ml", "Cava Gran Reserva - 750 ml", "Premium French Burgundy selection - 750 ml", "Premium Bordeaux vintage selection - 750 ml", "Luxury Napa Valley Cabernet selection - 750 ml"
];
const champagnes = [
  "Moet & Chandon Brut Imperial - 750 ml", "Moet & Chandon Ice Imperial - 750 ml", "Moet & Chandon Nectar Imperial - 750 ml", "Moet & Chandon Grand Vintage - 750 ml", "Moet & Chandon Rose Imperial - 750 ml", "Veuve Clicquot Yellow Label Brut - 750 ml", "Veuve Clicquot Rose - 750 ml", "Veuve Clicquot Vintage - 750 ml", "Veuve Clicquot La Grande Dame - 750 ml", "Ruinart Blanc de Blancs - 750 ml", "Ruinart Blanc de Noirs - 750 ml", "Ruinart Rose - 750 ml", "Laurent-Perrier La Cuvee Brut - 750 ml", "Laurent-Perrier Cuvee Rose - 750 ml", "Laurent-Perrier Grand Siecle - 750 ml", "Bollinger Special Cuvee - 750 ml", "Bollinger Rose - 750 ml", "Bollinger La Grande Annee - 750 ml", "Perrier-Jouet Grand Brut - 750 ml", "Perrier-Jouet Belle Epoque - 750 ml", "Perrier-Jouet Belle Epoque Rose - 750 ml", "Taittinger Brut Reserve - 750 ml", "Taittinger Prestige Rose - 750 ml", "Taittinger Comtes de Champagne - 750 ml", "Dom Perignon Vintage Brut - 750 ml", "Dom Perignon Rose Vintage - 750 ml", "Dom Perignon P2 Plenitude - 750 ml", "Krug Grande Cuvee - 750 ml", "Krug Rose - 750 ml", "Krug Vintage - 750 ml", "Louis Roederer Collection - 750 ml", "Louis Roederer Cristal - 750 ml", "Louis Roederer Cristal Rose - 750 ml", "Armand de Brignac Gold - 750 ml", "Armand de Brignac Rose - 750 ml", "Salon Blanc de Blancs - 750 ml", "Billecart-Salmon Brut Reserve - 750 ml", "Billecart-Salmon Brut Rose - 750 ml", "Pol Roger Brut Reserve - 750 ml", "Charles Heidsieck Brut Reserve - 750 ml"
];
const whiskies = [
  "Johnnie Walker Red Label - 700 ml", "Johnnie Walker Black Label 12 Year - 700 ml", "Johnnie Walker Double Black - 700 ml", "Johnnie Walker Green Label 15 Year - 700 ml", "Johnnie Walker Gold Label Reserve - 700 ml", "Johnnie Walker Aged 18 Year - 700 ml", "Johnnie Walker Blue Label - 750 ml", "Johnnie Walker Blue Label Ghost & Rare - 750 ml", "Chivas Regal 12 Year - 700 ml", "Chivas Regal Extra 13 Year - 700 ml", "Chivas Regal XV 15 Year - 700 ml", "Chivas Regal 18 Year - 700 ml", "Chivas Regal Mizunara - 700 ml", "Royal Salute 21 Year - 700 ml", "Royal Salute 25 Year - 700 ml", "Ballantine's Finest - 700 ml", "Ballantine's 17 Year - 700 ml", "Ballantine's 21 Year - 700 ml", "The Famous Grouse - 700 ml", "Monkey Shoulder - 700 ml", "Dewar's 12 Year - 700 ml", "Dewar's 18 Year - 700 ml", "The Macallan 12 Double Cask - 700 ml", "The Macallan 12 Sherry Oak - 700 ml", "The Macallan 15 Double Cask - 700 ml", "The Macallan 18 Sherry Oak - 700 ml", "The Macallan Rare Cask - 700 ml", "The Glenlivet 12 Year - 700 ml", "The Glenlivet 15 Year French Oak - 700 ml", "The Glenlivet 18 Year - 700 ml", "The Glenlivet 21 Year Archive - 700 ml", "Glenfiddich 12 Year - 700 ml", "Glenfiddich 15 Year Solera - 700 ml", "Glenfiddich 18 Year - 700 ml", "Glenfiddich 21 Year Gran Reserva - 700 ml", "Glenmorangie Original 10 Year - 700 ml", "Glenmorangie Lasanta 12 Year - 700 ml", "Glenmorangie Quinta Ruban 14 Year - 700 ml", "Glenmorangie 18 Year Extremely Rare - 700 ml", "Lagavulin 16 Year - 700 ml", "Laphroaig 10 Year - 700 ml", "Talisker 10 Year - 700 ml", "Talisker 18 Year - 700 ml", "Ardbeg 10 Year - 700 ml", "Monkey 47 Whisky Cask - 700 ml", "Jameson Irish Whiskey - 700 ml", "Jameson Black Barrel - 700 ml", "Redbreast 12 Year - 700 ml", "Redbreast 15 Year - 700 ml", "Green Spot Irish Whiskey - 700 ml", "Bushmills 10 Year - 700 ml", "Jack Daniel's Old No. 7 - 700 ml", "Jack Daniel's Gentleman Jack - 700 ml", "Jack Daniel's Single Barrel - 700 ml", "Jack Daniel's Tennessee Honey - 700 ml", "Jim Beam White Label - 700 ml", "Jim Beam Black 7 Year - 700 ml", "Maker's Mark Bourbon - 700 ml", "Maker's Mark 46 - 700 ml", "Woodford Reserve Bourbon - 700 ml", "Bulleit Bourbon - 700 ml", "Bulleit Rye - 700 ml", "Blanton's Single Barrel - 700 ml", "Buffalo Trace - 700 ml", "Hibiki Japanese Harmony - 700 ml", "Hibiki 21 Year - 700 ml", "Yamazaki Distiller's Reserve - 700 ml", "Yamazaki 12 Year - 700 ml", "Hakushu Distiller's Reserve - 700 ml", "Hakushu 12 Year - 700 ml", "Nikka From the Barrel - 500 ml", "Nikka Coffey Grain - 700 ml", "Mars Iwai Tradition - 700 ml", "Mekhong Thai Whisky - 700 ml", "SangSom Special Rum Whisky - 700 ml", "Hong Thong Thai Spirit - 700 ml", "Blend 285 Thai Whisky - 700 ml", "Hennessy VSOP Cognac - 700 ml", "Hennessy XO Cognac - 700 ml", "Remy Martin XO Cognac - 700 ml"
];
const rums = [
  "Bacardi Carta Blanca - 700 ml", "Bacardi Carta Oro Gold - 700 ml", "Bacardi Carta Negra - 700 ml", "Bacardi Reserva Ocho 8 Year - 750 ml", "Bacardi Gran Reserva Especial - 750 ml", "Captain Morgan White Rum - 700 ml", "Captain Morgan Gold Spiced - 700 ml", "Captain Morgan Dark Rum - 700 ml", "Captain Morgan Private Stock - 750 ml", "Havana Club 3 Year - 700 ml", "Havana Club 7 Años - 700 ml", "Havana Club Seleccion de Maestros - 700 ml", "Malibu Original Coconut - 700 ml", "Malibu Black - 700 ml", "Mount Gay Eclipse - 700 ml", "Mount Gay Black Barrel - 700 ml", "Mount Gay XO - 700 ml", "Diplomatico Mantuano - 700 ml", "Diplomatico Reserva Exclusiva - 700 ml", "Diplomatico Ambassador - 700 ml", "Ron Zacapa 23 - 750 ml", "Ron Zacapa XO - 750 ml", "Appleton Estate Signature - 700 ml", "Appleton Estate 12 Rare Casks - 700 ml", "Appleton Estate 15 Black River - 700 ml", "Plantation Original Dark - 700 ml", "Plantation XO 20th Anniversary - 700 ml", "Kraken Black Spiced Rum - 700 ml", "Sailor Jerry Spiced Rum - 700 ml", "Ron Abuelo 12 Year - 700 ml", "Foursquare Exceptional Cask - 700 ml", "Chalong Bay White Rum - 700 ml", "Chalong Bay Patong Series - 700 ml", "Phraya Elements - 700 ml", "Phraya Gold - 700 ml", "SangSom Special Rum - 700 ml", "Mekhong Thai Spirit - 700 ml", "Magic Alambic Thai Rum - 700 ml", "Thai premium rum reserve - 700 ml"
];
const vodkas = [
  "Smirnoff No. 21 - 700 ml", "Smirnoff Black - 700 ml", "Smirnoff Vanilla - 700 ml", "Smirnoff Raspberry - 700 ml", "Absolut Original - 700 ml", "Absolut Elyx - 700 ml", "Absolut Citron - 700 ml", "Absolut Vanilla - 700 ml", "Absolut Mango - 700 ml", "Absolut Raspberri - 700 ml", "Grey Goose - 700 ml", "Grey Goose La Poire - 700 ml", "Grey Goose Le Citron - 700 ml", "Grey Goose Altius - 700 ml", "Belvedere Pure - 700 ml", "Belvedere Organic Infusions Pear & Ginger - 700 ml", "Belvedere Organic Infusions Blackberry & Lemongrass - 700 ml", "Beluga Noble - 700 ml", "Beluga Gold Line - 700 ml", "Beluga Allure - 700 ml", "Ketel One - 700 ml", "Ketel One Citroen - 700 ml", "Ciroc Original - 700 ml", "Ciroc Peach - 700 ml", "Ciroc Apple - 700 ml", "Ciroc Pineapple - 700 ml", "Crystal Head - 700 ml", "Stolichnaya Premium - 700 ml", "Stolichnaya Elit - 700 ml", "Russian Standard Platinum - 700 ml", "Finlandia - 700 ml", "Haku Japanese Craft Vodka - 700 ml", "Chopin Potato Vodka - 700 ml", "Tito's Handmade Vodka - 700 ml", "Skyy Vodka - 700 ml", "Ketel One Botanical Peach & Orange Blossom - 700 ml"
];
const gins = [
  "Gordon's London Dry - 700 ml", "Gordon's Pink - 700 ml", "Gordon's Sicilian Lemon - 700 ml", "Beefeater London Dry - 700 ml", "Beefeater 24 - 700 ml", "Beefeater Pink - 700 ml", "Bombay Sapphire - 700 ml", "Bombay Sapphire East - 700 ml", "Bombay Sapphire Premier Cru - 700 ml", "Tanqueray London Dry - 700 ml", "Tanqueray No. Ten - 700 ml", "Tanqueray Rangpur Lime - 700 ml", "Tanqueray Sevilla Orange - 700 ml", "Tanqueray Blackcurrant Royale - 700 ml", "Hendrick's - 700 ml", "Hendrick's Orbium - 700 ml", "Hendrick's Neptunia - 700 ml", "Monkey 47 Schwarzwald Dry - 500 ml", "Monkey 47 Distiller's Cut - 500 ml", "The Botanist Islay Dry Gin - 700 ml", "Roku Japanese Craft Gin - 700 ml", "Ki No Bi Kyoto Dry Gin - 700 ml", "Suntory Roku Sakura Bloom - 700 ml", "Plymouth Gin - 700 ml", "Sipsmith London Dry - 700 ml", "Sipsmith V.J.O.P. - 700 ml", "Martin Miller's Westbourne Strength - 700 ml", "Nolet's Silver - 700 ml", "Gin Mare - 700 ml", "Engine Organic Gin - 500 ml", "Chalong Bay Dry Gin - 700 ml", "Iron Balls Gin - 700 ml", "Iron Balls Botanical Gin - 700 ml", "Bangkok Gin - 700 ml", "Siam 43 Gin - 700 ml", "Mekhong Thai Botanical Gin - 700 ml", "Nikka Coffey Gin - 700 ml", "Elephant Gin - 500 ml", "Monkey 47 Barrel Cut - 500 ml"
];
const liqueurs = [
  "Baileys Original Irish Cream - 700 ml", "Baileys Salted Caramel - 700 ml", "Baileys Espresso Creme - 700 ml", "Baileys Strawberries & Cream - 700 ml", "Kahlua Original Coffee Liqueur - 700 ml", "Kahlua Salted Caramel - 700 ml", "Jagermeister - 700 ml", "Jagermeister Manifest - 700 ml", "Jagermeister Cold Brew Coffee - 700 ml", "Cointreau - 700 ml", "Grand Marnier Cordon Rouge - 700 ml", "Grand Marnier Cuvee du Centenaire - 700 ml", "Amaretto Disaronno Originale - 700 ml", "Disaronno Velvet - 700 ml", "Sambuca Molinari - 700 ml", "Sambuca Luxardo - 700 ml", "Drambuie - 700 ml", "Midori Melon Liqueur - 700 ml", "Malibu Original Coconut - 700 ml", "Malibu Passion Fruit - 700 ml", "Southern Comfort Original - 700 ml", "Triple Sec - 700 ml", "Galliano L'Autentico - 700 ml", "Chartreuse Verte - 700 ml", "Chartreuse Jaune - 700 ml", "Benedictine D.O.M. - 700 ml", "Frangelico Hazelnut - 700 ml", "Limoncello Villa Massa - 700 ml", "Chambord Black Raspberry - 700 ml", "St-Germain Elderflower - 700 ml", "Pernod Absinthe Superieure - 700 ml", "Luxardo Maraschino - 700 ml", "Creme de Cassis - 700 ml", "Creme de Menthe - 700 ml", "Pisco Capel Reservado - 700 ml"
];
const aperitifs = [
  "Aperol - 700 ml", "Campari - 700 ml", "Martini Rosso - 750 ml", "Martini Bianco - 750 ml", "Martini Extra Dry - 750 ml", "Martini Fiero - 750 ml", "Cinzano Rosso - 750 ml", "Cinzano Bianco - 750 ml", "Cocchi Americano - 750 ml", "Cocchi Vermouth di Torino - 750 ml", "Lillet Blanc - 750 ml", "Lillet Rose - 750 ml", "Pimm's No. 1 - 700 ml", "Pernod Anise - 700 ml", "Ricard Pastis - 700 ml", "Fernet-Branca - 700 ml", "Branca Menta - 700 ml", "Cynar Artichoke Aperitif - 700 ml", "Noilly Prat Extra Dry - 750 ml", "Select Aperitivo - 700 ml", "Amaro Montenegro - 700 ml", "Amaro Averna - 700 ml", "Amaro Nonino Quintessentia - 700 ml", "Amaro del Capo - 700 ml", "Ramazzotti Amaro - 700 ml", "Vecchio Amaro del Capo Riserva - 700 ml", "Grappa Nonino Chardonnay - 700 ml", "Grappa di Barolo - 700 ml", "Marc de Champagne - 700 ml", "Ouzo 12 - 700 ml", "Metaxa 7 Stars - 700 ml", "Suze Gentiane - 700 ml"
];

export const catalogueCategories: CatalogueCategory[] = [
  { name: "Thai starters & salads", group: "food", description: "Bright, aromatic beginnings for a Thai-led package.", products: pricedProducts(thaiStarters, 280), indicativeFrom: 280 },
  { name: "Thai soups", group: "food", description: "Broths and hot-and-sour bowls with adjustable heat.", products: pricedProducts(thaiSoups, 320), indicativeFrom: 320 },
  { name: "Thai curries", group: "food", description: "Coconut, spice, herbs, and slow-cooked depth.", products: pricedProducts(thaiCurries, 380), indicativeFrom: 380 },
  { name: "Thai rice", group: "food", description: "Rice dishes and fragrant staples for complete packages.", products: pricedProducts(thaiRice, 240), indicativeFrom: 240 },
  { name: "Thai noodles", group: "food", description: "Street-food classics and comforting noodle bowls.", products: pricedProducts(thaiNoodles, 300), indicativeFrom: 300 },
  { name: "Thai seafood", group: "food", description: "Prawns, fish, squid, crab, and seafood sharing options.", products: pricedProducts(thaiSeafood, 520), indicativeFrom: 520 },
  { name: "Thai meat & chicken", group: "food", description: "Grilled, stir-fried, and slow-cooked meat selections.", products: pricedProducts(thaiMeat, 420), indicativeFrom: 420 },
  { name: "International & Western", group: "food", description: "Burgers, pizza, pasta, steak, and Western breakfast.", products: pricedProducts(western, 420), indicativeFrom: 420 },
  { name: "Asian favourites", group: "food", description: "Japanese, Korean, Chinese, Vietnamese, Singaporean, and Malaysian dishes.", products: pricedProducts(asian, 420), indicativeFrom: 420 },
  { name: "Vegetarian & healthy", group: "food", description: "Clearly marked vegetarian-friendly bowls, salads, tofu, and vegetable dishes.", products: pricedProducts(healthy, 300), indicativeFrom: 300, vegetarianFriendly: true },
  { name: "Snacks & desserts", group: "food", description: "Sides, small bites, Thai sweets, and familiar desserts.", products: pricedProducts(snacksDesserts, 180), indicativeFrom: 180 },
  { name: "Soft drinks, coffee, tea & juices", group: "drinks", description: "Thai drinks, hot coffee, tea, fresh juices, and soft drinks.", products: pricedProducts(drinks, 90), indicativeFrom: 90 },
  { name: "Beer", group: "alcohol", description: "Premium domestic, imported, craft, and collectible beers subject to Thai legal and delivery controls.", products: pricedProducts(beers, 180), indicativeFrom: 180 },
  { name: "Wine", group: "alcohol", description: "Premium and fine still wines from established producers; availability remains subject to legal controls.", products: pricedProducts(wines, 1200), indicativeFrom: 1200 },
  { name: "Champagne & sparkling wine", group: "alcohol", description: "Prestige Champagne and sparkling selections for celebrations and VIP occasions.", products: pricedProducts(champagnes, 3200), indicativeFrom: 3200 },
  { name: "Whisky", group: "alcohol", description: "Single malts, blended Scotch, Japanese whisky, bourbon, and premium cognac.", products: pricedProducts(whiskies, 2600), indicativeFrom: 2600 },
  { name: "Rum", group: "alcohol", description: "Aged, sipping, Caribbean, and premium spiced rums.", products: pricedProducts(rums, 1800), indicativeFrom: 1800 },
  { name: "Vodka", group: "alcohol", description: "Premium and ultra-premium vodkas for neat service and cocktails.", products: pricedProducts(vodkas, 1800), indicativeFrom: 1800 },
  { name: "Gin", group: "alcohol", description: "Contemporary botanical, London dry, Japanese, and small-batch gins.", products: pricedProducts(gins, 1800), indicativeFrom: 1800 },
  { name: "Liqueurs", group: "alcohol", description: "Classic cream, herbal, fruit, coffee, and digestif liqueurs.", products: pricedProducts(liqueurs, 1100), indicativeFrom: 1100 },
  { name: "Aperitifs & digestifs", group: "alcohol", description: "Vermouth, aperitivo, bitters, and after-dinner selections for a complete bar catalogue.", products: pricedProducts(aperitifs, 900), indicativeFrom: 900 },
];

export const servicePeriods = ["Breakfast", "Lunch", "Dinner", "Snacks", "Seasonal events"] as const;

export const alcoholControls = ["Age verification required", "Compliance status per product", "Legal sale availability flag", "Delivery restrictions by route", "Responsible-sale warning shown at checkout", "Never automatically included in a food-only package"] as const;

export const menuRotation = [
  { week: "Week 1", days: [["Monday", "Pad Kra Pao Chicken"], ["Wednesday", "Green Curry Chicken"], ["Friday", "Grilled Seafood"], ["Sunday", "Premium Steak"]] },
  { week: "Week 2", days: [["Monday", "Pad Thai"], ["Wednesday", "Massaman Beef"], ["Friday", "Thai Seafood BBQ"], ["Sunday", "Pasta or Steak"]] },
] as const;
