import type { Metadata } from "next";
import Link from "next/link";
import { membershipPlans } from "@/lib/membership-plans";
import { PageHeader } from "@/components/site/page-header";

export const metadata: Metadata = { title: "Pricing", description: "Current Sanbay Fusion membership fees and Standard Meal allowances for 1–12 selected service months.", alternates: { canonical: "/pricing" } };
const baht = (amount: number) => "฿" + amount.toLocaleString("en-US", { maximumFractionDigits: 0 });

export default function PricingPage() {
  return <div className="pb-28"><PageHeader eyebrow="Membership pricing" title="More months. Better monthly value." lead="One membership fee for your selected service months. Optional prepaid packages and additional orders are priced separately." /><div className="mx-auto max-w-5xl px-5 sm:px-8">
    <div className="overflow-x-auto border border-border/60"><table className="w-full min-w-[640px] text-left text-sm"><caption className="p-5 text-left text-foreground/75">Current plan fees in Thai baht. Effective monthly fees are rounded for comparison; each Standard Meal allowance applies once in each selected month.</caption><thead className="bg-gold/10"><tr>{["Plan", "Total membership fee", "Approx. fee per month", "Standard Meal allowance"].map(label => <th key={label} scope="col" className="p-4 font-medium">{label}</th>)}</tr></thead><tbody className="divide-y divide-border/50">{membershipPlans.map(plan => <tr key={plan.id}><th scope="row" className="p-4 font-normal"><Link className="text-gold underline underline-offset-4" href={"/plans/" + plan.slug}>{plan.name}</Link></th><td className="p-4">{baht(plan.price)}</td><td className="p-4">{baht(plan.price / plan.durationMonths)}</td><td className="p-4">{baht(plan.includedBenefit.menuValue)} / selected month</td></tr>)}</tbody></table></div>
    <div className="mt-10 grid gap-6 md:grid-cols-2"><section className="border border-border/60 p-7"><h2 className="font-display text-3xl">Optional prepaid packages</h2><p className="mt-4 text-sm leading-7 text-foreground/75">Monthly products use unit price × monthly quantity × selected service months. Monthly add-ons follow the same rule; one-time add-ons are charged once. Review your exact total before submitting an application.</p></section><section className="border border-border/60 p-7"><h2 className="font-display text-3xl">Additional orders and events</h2><p className="mt-4 text-sm leading-7 text-foreground/75">Additional member orders use current catalogue prices. Standard Meal food above your allowance is paid at checkout. Meeting requests and event briefs are enquiries; the team confirms any event quote separately.</p></section></div>
    <p className="mt-8 text-sm leading-7 text-foreground/75">Submitting an application does not collect the membership fee. Approval makes the invoice ready for staff collection; activation requires verified successful payment. Card verification is a separate refundable USD $2 payment. Online payments currently operate in test mode; live card payments are not available.</p>
    <div className="mt-8 flex flex-wrap gap-6"><Link className="text-gold underline" href="/plans">Choose a plan</Link><Link className="text-gold underline" href="/catalogue">Explore the catalogue</Link><Link className="text-gold underline" href="/how-it-works">How it works</Link></div>
  </div></div>;
}
